#!/usr/bin/env python3
"""Is `clamp_frac_state_scalar_500` a model pathology or a property of the loss?

The FNO run reports this clamp active on 18% of samples and still firing at the
final epoch, where every other clamp in every other cell is a startup transient.
That looks like an FNO defect. This checks whether it is one.

WHAT THE CLAMP IS. In `ode_physics_loss_shared` — the loss the shared physics
trainer uses, and therefore the loss every C-11 baseline trains under — the
prediction is truncated before the residual is formed:

    xp_clamped = xp.detach().clamp(0, 500)
    f_rhs = fast_rhs_torch(xp_clamped, u_t)
    res = (dxdt - f_rhs) ** 2

A **scalar** ceiling of 500 applied to every state alike. `ode_physics_loss` —
the loss `train_v34` uses, i.e. what COD and Ablation A train under — instead uses
the per-state vector `STATE_CLAMP_HI = [200, 500, 200, 1000, 3000, 8000]`.

`cod/training/losses.py` already records the consequence in its own docstring:
"A scalar ceiling of 500 truncates CO (typical ~1e2-1e3 ppm) and CO2 (~1e3 ppm)
hard, so the shared trainer's gas residuals are formed at a clamped state far
more often."

So the question is not whether FNO is badly behaved. It is how much of the
frozen training distribution lies above 500 in **ground truth**, because any
prediction that is *correct* on those samples is clamped anyway. That is
measurable without a model, and it applies identically to every cell trained
with the shared loss.

Run:  python audit_port/scripts/30_scalar500_clamp.py
Exit: 0 if ground truth stays under the scalar ceiling, 1 if the ceiling
      truncates physically correct states — in which case the reported clamp
      fraction is a property of the loss, not of the architecture.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from cod.data.generate import (  # noqa: E402
    build_realistic_test_set, generate_realistic_training_set,
    rk45_ground_truth,
)
from cod.data.physics import STATE_NAMES_FAST, TW  # noqa: E402
from cod.data.realistic import RealisticParams  # noqa: E402
from cod.training.losses import STATE_CLAMP_HI_NP  # noqa: E402

CONFIG = ROOT / "configs" / "example_cod_seed1.yaml"
OUT = ROOT / "audit_port" / "SCALAR500_CLAMP.md"
SCALAR = 500.0
N_CASES = 300
NQ = 60


def main() -> int:
    params = RealisticParams.from_config(
        yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
        ["distribution"]["sampler"]["params"])

    # Initial conditions as the trainer sees them.
    print(f"[data] {N_CASES} training ICs from the frozen sampler")
    ts = generate_realistic_training_set(n_ic=N_CASES, seed=42, params=params)
    x0s = np.asarray(ts.x0s, float)

    # And the whole trajectory, since the residual is formed at collocation
    # points across the window, not only at t=0.
    print(f"[data] RK45 trajectories for {N_CASES} cases")
    cases = build_realistic_test_set(n_test=N_CASES, seed=999, params=params)
    tq = np.linspace(0.0, TW, NQ)
    traj = np.stack([rk45_ground_truth(c.x0, c.K_sensors, c.Ta_sensors, tq,
                                       T=TW) for c in cases])

    print(f"\n{'state':>10} {'IC max':>12} {'traj max':>12} "
          f"{'% traj pts > 500':>17} {'per-state _hi':>14}")
    rows = []
    for i, name in enumerate(STATE_NAMES_FAST[:6]):
        ic_max = float(x0s[:, i].max())
        tr = traj[:, :, i]
        tr_max = float(tr.max())
        frac = float((tr > SCALAR).mean())
        rows.append({"state": name, "ic_max": ic_max, "traj_max": tr_max,
                     "frac_over": frac, "hi": float(STATE_CLAMP_HI_NP[i])})
        print(f"{name:>10} {ic_max:12.4g} {tr_max:12.4g} {100 * frac:16.2f}% "
              f"{STATE_CLAMP_HI_NP[i]:14.0f}")

    # The quantity the diagnostic actually reports: fraction of (case, time)
    # points where ANY state exceeds the scalar ceiling.
    any_over = float((traj > SCALAR).any(axis=-1).mean())
    ic_any = float((x0s > SCALAR).any(axis=-1).mean())
    print(f"\nground-truth points with ANY state > {SCALAR:g}: "
          f"{100 * any_over:.2f}%   (initial conditions: {100 * ic_any:.2f}%)")

    culprits = [r for r in rows if r["frac_over"] > 0.001]
    md = ["# Is the scalar-500 clamp a model defect or a property of the loss?\n",
          "Generated by `audit_port/scripts/30_scalar500_clamp.py`. Ground truth "
          "only — no model is involved, so this holds for every cell trained "
          "with the shared physics loss.\n",
          "## What the clamp is\n",
          "`ode_physics_loss_shared` truncates the prediction with a **scalar** "
          "`clamp(0, 500)` before forming the residual. `ode_physics_loss`, which "
          "`train_v34` uses, instead applies the per-state vector "
          "`[200, 500, 200, 1000, 3000, 8000]`. So COD and Ablation A "
          "(`loop: train_v34`) and the six C-11 baselines (`loop: train_physics`) "
          "are **not** trained under the same clamp.\n",
          "## How much of the frozen distribution is above the ceiling\n",
          f"| state | IC max | trajectory max | % of trajectory points > {SCALAR:g} "
          "| per-state ceiling |", "|---|---|---|---|---|"]
    for r in rows:
        mark = " **<-- truncated**" if r["frac_over"] > 0.001 else ""
        md.append(f"| `{r['state']}` | {r['ic_max']:.4g} | {r['traj_max']:.4g} | "
                  f"{100 * r['frac_over']:.2f}%{mark} | {r['hi']:.0f} |")
    md.append("")
    md.append(f"Points where **any** state exceeds {SCALAR:g}: "
              f"**{100 * any_over:.2f}%** of trajectory points, "
              f"{100 * ic_any:.2f}% of initial conditions.\n")

    md.append("## Reading\n")
    if culprits:
        names = ", ".join(f"`{r['state']}`" for r in culprits)
        md.append(f"**The ceiling truncates physically correct states**: {names} "
                  "exceed 500 in ground truth, well inside their own per-state "
                  "ceilings. A model predicting those values *correctly* is "
                  "clamped anyway, and its residual is then formed at a state it "
                  "did not predict.\n")
        md.append("So `clamp_frac_state_scalar_500` firing throughout training "
                  "is **a property of the shared loss on this distribution, not "
                  "of the architecture**. It should be expected in every cell "
                  "using `loop: train_physics` — FNO, MIONet and S-DeepONet, all "
                  "six — and to be absent in COD and Ablation A, which use "
                  "`train_v34` and its per-state vector. That is exactly the "
                  "pattern observed, and it is not evidence about FNO.\n")
        md.append("**Consequence for C-11.** The method and the baselines are "
                  "trained under different clamps, and the baselines' is the "
                  "tighter one on the gas states. That is a systematic "
                  "disadvantage to every baseline in the matrix, and it is not "
                  "an architectural difference. It has to be resolved before the "
                  "remaining cells run, or the comparison measures the loss "
                  "rather than the architecture.\n")
    else:
        md.append("Ground truth stays under the scalar ceiling, so a model "
                  "hitting it is predicting non-physical values and the clamp "
                  "fraction is evidence about that model.\n")

    OUT.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"\nWrote {OUT}")
    if culprits:
        print("\nCLAMP TRUNCATES CORRECT STATES — it is a property of the loss:")
        for r in culprits:
            print(f"  {r['state']}: {100 * r['frac_over']:.2f}% of trajectory "
                  f"points above {SCALAR:g}, own ceiling is {r['hi']:.0f}")
        return 1
    print("\nPASS — ground truth stays under the scalar ceiling")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
